# Generated by Django 4.0.3 on 2022-06-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_salerperson_sellerperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecord',
            old_name='automobile',
            new_name='vin',
        ),
    ]
