# Generated by Django 4.0.3 on 2022-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_rename_automobile_salerecord_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='status',
            field=models.BooleanField(),
        ),
    ]
