# Generated by Django 4.0.3 on 2022-06-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_rename_automobile_salerecord_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecord',
            old_name='sales_person',
            new_name='seller',
        ),
    ]
